project:
  type: website
  output-dir: docs

website:
  title: "NK blogs"
  navbar:
    left:
      - text: "Blog Posts"
        file: index.qmd
      - about.qmd
    right:
      - icon: envelope-fill
        href: mailto:nick.kalenichenko@gmail.com
      - icon: github
        href: https://github.com/nickkalen
      - icon: linkedin
        href: https://www.linkedin.com/in/nickkalenichenko/
format:
  html:
    theme: zephyr
    css: styles.css

execute:
  freeze: auto

